
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unpanmmpkzlmverkiwpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucGFubW1wa3psbXZlcmtpd3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDI1MTYsImV4cCI6MjA1NzYxODUxNn0.-dBy60MM_G6vMtcun8dz1IPY2J7VCLMzDO26oqzb5FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
